// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// coordinate_descent
arma::vec coordinate_descent(const arma::mat& X0, const arma::vec& y0, double lambda);
RcppExport SEXP _Lasso_coordinate_descent(SEXP X0SEXP, SEXP y0SEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(coordinate_descent(X0, y0, lambda));
    return rcpp_result_gen;
END_RCPP
}
// proximal_operator
arma::vec proximal_operator(const arma::mat X0, const arma::vec y0, double lambda);
RcppExport SEXP _Lasso_proximal_operator(SEXP X0SEXP, SEXP y0SEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(proximal_operator(X0, y0, lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Lasso_coordinate_descent", (DL_FUNC) &_Lasso_coordinate_descent, 3},
    {"_Lasso_proximal_operator", (DL_FUNC) &_Lasso_proximal_operator, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_Lasso(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
