# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coordinate_descent <- function(X0, y0, lambda) {
    .Call('_Lasso_coordinate_descent', PACKAGE = 'Lasso', X0, y0, lambda)
}

proximal_operator <- function(X0, y0, lambda) {
    .Call('_Lasso_proximal_operator', PACKAGE = 'Lasso', X0, y0, lambda)
}

